# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings
name: UNSW Vovinam
markdown: redcarpet
highliter: pygments
paginate: 10 # pagination basted on number of posts
exclude: ["Gemfile", "Gemfile.lock", "README.md", 'sass', 'watch.sh', 'style.scss', 'bootstrap.scss'] # files to exclude
baseurl: "/vovinam_site"
